"""feat(reviews): add enrollment_id, is_hidden, rename comment to body

Revision ID: de164c1227eb
Revises: 8c183f3f3ff0
Create Date: 2026-06-18 06:00:27.804917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de164c1227eb'
down_revision: Union[str, Sequence[str], None] = '8c183f3f3ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('enrollment_id', sa.UUID(), nullable=False))
    op.add_column('reviews', sa.Column('body', sa.Text(), nullable=False))
    op.add_column('reviews', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reviews', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'is_hidden')
    op.drop_column('reviews', 'body')
    op.drop_column('reviews', 'enrollment_id')
    # ### end Alembic commands ###
