"""add lesson_attachments table

Revision ID: e0914197c80a
Revises: af3e08475ac5
Create Date: 2026-06-16 02:23:11.124526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0914197c80a'
down_revision: Union[str, Sequence[str], None] = 'af3e08475ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_attachments',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_attachments_lesson_id'), 'lesson_attachments', ['lesson_id'], unique=False)
    op.drop_index(op.f('ix_courses_search_vector'), table_name='courses', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_courses_search_vector'), 'courses', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_lesson_attachments_lesson_id'), table_name='lesson_attachments')
    op.drop_table('lesson_attachments')
    # ### end Alembic commands ###
