"""feat(certificates): add certificates table

Revision ID: efa4674c12d4
Revises: 9e8efff84019
Create Date: 2026-06-22 00:08:08.912329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa4674c12d4'
down_revision: Union[str, Sequence[str], None] = '9e8efff84019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('course_title', sa.String(length=255), nullable=False),
    sa.Column('instructor_name', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_uuid', sa.UUID(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_uuid')
    )
    op.create_index(op.f('ix_certificates_enrollment_id'), 'certificates', ['enrollment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificates_enrollment_id'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###
